apiVersion: v1
kind: Pod
metadata:
  name: prepwp
  labels:
    app: wordpress
spec:
   containers:
   - image: registry.ng.bluemix.net/payega/prepwp
     name: prepwp
     env:
     - name: DOMAIN
       valueFrom:
         configMapKeyRef:
           # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
           name: domain-config
           # Specify the key associated with the value
           key: domain      
     volumeMounts:
     - name: certs
       mountPath: /var/certs            
   volumes:
   - name: certs
     hostPath:
       path: /tmp/var/certs          