apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30180
      name: nossl
    - port: 443
      targetPort: 443
      nodePort: 30143
      name: ssl
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-lv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 19Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-lv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: 4.8.0-php7.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        # - name: WORDPRESS_DB_USER
        #   value: admin
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt        
        ports:
        - containerPort: 80
          name: nossl
        - containerPort: 443
          name: ssl          
        volumeMounts:
        - name: wordpress-local-storage
          mountPath: /var/www/html
        - name: apache2
          mountPath: /etc/apache2            
      volumes:
      - name: wordpress-local-storage
        persistentVolumeClaim:
          claimName: wp-lv-claim
      - name: apache2
        persistentVolumeClaim:
          claimName: apache-lv-claim        