apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30180
    - port: 443
      targetPort: 443
      nodePort: 30143      
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-lv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: registry.ng.bluemix.net/payega/wordpress:4.7.5-php7.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        # - name: WORDPRESS_DB_USER
        #   value: admin
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        # Define the environment variable
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: domain-config
              # Specify the key associated with the value
              key: domain              
        ports:
        - containerPort: 80
          name: wordpress
        - containerPort: 443
          name: wordpressssl          
        volumeMounts:
        - name: wordpress-local-storage
          mountPath: /var/www/html
        - name: certs
          mountPath: /var/certs            
      volumes:
      - name: wordpress-local-storage
        persistentVolumeClaim:
          claimName: wp-lv-claim
      - name: usersdb
        hostPath:
          path: /tmp/var/certs          